# Generated by Django 3.1.7 on 2021-03-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ourmembers2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurMembers',
        ),
    ]
