# Generated by Django 3.1.7 on 2021-03-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_ourmembers3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurMembers2',
        ),
    ]
