# Generated by Django 3.1.7 on 2021-03-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_ourcustomers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_comment', models.TextField(blank=True)),
                ('project_w_address', models.URLField(blank=True)),
                ('project_is_ready', models.BooleanField(default=False)),
                ('project_end_date', models.DateField(blank=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ourmembers3')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ourcustomers2')),
            ],
        ),
    ]
