# Generated by Django 3.1.7 on 2021-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
